name: Vercel Production Deployment
on:
  push:
    branches-ignore:
      - main
jobs:
  cypress-run:
          runs-on: ubuntu-latest
          steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                working-directory: wordtrack
                command: npm run test & wait-on http://localhost:3000
            # Install NPM dependencies, cache them correctly
            # and run all Cypress tests
            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                working-directory: wordtrack
                command: npx cypress run 
                browser: chrome